name: skill_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.0
  google_generative_ai: ^0.4.7
  http: ^1.2.0
  shared_preferences: ^2.2.0 
  intl: ^0.18.1  # For date formatting
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter:
    sdk: flutter

  # Firebase packages (latest stable compatible versions)
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Add assets here if needed
  # assets:
  #   - assets/images/
