// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa4r8V4yYvtZZEbap98X9fDMwKUb4_Xcg',
    appId: '1:164150403704:web:2b87fd9442359a546a038d',
    messagingSenderId: '164150403704',
    projectId: 'skill-tracker-9ca6b',
    authDomain: 'skill-tracker-9ca6b.firebaseapp.com',
    storageBucket: 'skill-tracker-9ca6b.firebasestorage.app',
    measurementId: 'G-6496TFT3TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKywO8iv8eSqW-FukwFQjEtifByeSUeWw',
    appId: '1:164150403704:android:4d1a4ed28012fd856a038d',
    messagingSenderId: '164150403704',
    projectId: 'skill-tracker-9ca6b',
    storageBucket: 'skill-tracker-9ca6b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa4r8V4yYvtZZEbap98X9fDMwKUb4_Xcg',
    appId: '1:164150403704:web:4dee51834e7170d36a038d',
    messagingSenderId: '164150403704',
    projectId: 'skill-tracker-9ca6b',
    authDomain: 'skill-tracker-9ca6b.firebaseapp.com',
    storageBucket: 'skill-tracker-9ca6b.firebasestorage.app',
    measurementId: 'G-K594PKY3ST',
  );
}
