// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDarpI7x1DFUnxvjHv_j15pPGkad-55rYA',
    appId: '1:1234567890:web:1234567890abcdef', // USER_MUST_UPDATE_THIS_FROM_CONSOLE
    messagingSenderId: '229249602016',
    projectId: 'skilltracker-e5fc6',
    authDomain: 'skilltracker-e5fc6.firebaseapp.com',
    storageBucket: 'skilltracker-e5fc6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCENSsjWtwj7w4bq8FULgxcOUbnRdiRIGg',
    appId: '1:229249602016:android:a14ba2c743ff56cac21b85',
    messagingSenderId: '229249602016',
    projectId: 'skilltracker-e5fc6',
    storageBucket: 'skilltracker-e5fc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSFco_gyggLUDyp6v0033Y6QnmpP5vLJY',
    appId: '1:229249602016:ios:4d6375c42532786cc21b85',
    messagingSenderId: '229249602016',
    projectId: 'skilltracker-e5fc6',
    storageBucket: 'skilltracker-e5fc6.firebasestorage.app',
    iosClientId: '229249602016-iosclientid.apps.googleusercontent.com', // Placeholder derived from senderId
    iosBundleId: 'com.example.skillTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSFco_gyggLUDyp6v0033Y6QnmpP5vLJY',
    appId: '1:229249602016:ios:4d6375c42532786cc21b85', // Reuse iOS app ID for macOS often
    messagingSenderId: '229249602016',
    projectId: 'skilltracker-e5fc6',
    storageBucket: 'skilltracker-e5fc6.firebasestorage.app',
    iosClientId: '229249602016-iosclientid.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillTracker',
  );
}
